### ISSUE TITLE
The Grand Tech Stack Checklist

### ISSUE THREAD

**Issue by ennukee** [enragednuke/osusume-frontend#6]
This is the checklist I'll go through when starting to redo the osusume frontend from the ground up.
 
### Step 1 - the great cleansing
- [ ] Wipe the slate clean -- absolutely nothing is worth keeping

### Initial Tech Stack
- [ ] React Hooks 
- [ ] Concurrent Mode (& Suspense)
- [ ] Next.js (if it supports hooks + concurrent mode, that feature will be quite important going forward)
- [ ] TypeScript support
- [ ] React Spring
- [ ] D3 (if using data charts), probably

### End Goals
- [ ] Mobile support
- [ ] Full accessibility -- near 100% on google chrome audit categories for all categories
- [ ] Same vein -- achieve near full coverage on [axe accessibility](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) metrics
- [ ] Maximal speed -- All non-backend reliant operations should render in less than 1-2 seconds if possible. All individual components should take no more than 0.16s to render unless reliant on backend queries.
- [ ] Full test coverage on every component and utility method using React Testing Library
  - [ ] Similarly, all components and methods should not rely on state unless it also directly manipulates the state -- this allows for much more extractions which can equal better test coverage of internal utility that is otherwise untestable in Hooks w/ RTL.
- [ ] Understand and setup webpack configs to allow me to do importants like `import X from 'Utils/X` in the code
